CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE posts_super WITH LOGIN PASSWORD 'posts_super' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE posts_database;
GRANT ALL PRIVILEGES ON DATABASE posts_database TO posts_super;
GRANT ALL PRIVILEGES ON DATABASE posts_database TO super;
