INSERT INTO post(id, title, description, content, read_minutes, publish_date)
VALUES ('quarkus-annotations', 'Quarkus Annotations', 'Consectetur incididunt ut labore et dolore magna aliqua', 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. ', 1, '1995-12-17');
INSERT INTO post(id, title, description, content, read_minutes, publish_date)
VALUES ('quarkus-command-mode', 'Quarkus Command Mode', 'Consectetur adipiscing elit, sed do eiusmod adipiscing elit, sed do eiusmod tempor tempor incididunt ut labore et dolore magna aliqua', 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. ', 2, '1995-12-18');
INSERT INTO post(id, title, description, content, read_minutes, publish_date)
VALUES ('quarkus-microservice-project', 'Quarkus Microservice Project', 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua', 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. ', 3, '1995-12-19');

INSERT INTO tag(post_id, tag_name) VALUES ('quarkus-annotations', 'Quarkus');
INSERT INTO tag(post_id, tag_name) VALUES ('quarkus-annotations', 'Annotations');
INSERT INTO tag(post_id, tag_name) VALUES ('quarkus-command-mode', 'Command');
INSERT INTO tag(post_id, tag_name) VALUES ('quarkus-command-mode', 'Mode');
INSERT INTO tag(post_id, tag_name) VALUES ('quarkus-microservice-project', 'Project');
